import os
import time

from dotenv import load_dotenv
from google import genai
from rich import print

# Load environment variables from the .env file
load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError("GEMINI_API_KEY is not configured.")

# Initialize the Gemini client
gemini_client = genai.Client(api_key=API_KEY)

# Store the conversation history
chat_history = []
MAX_HISTORY_LENGTH = 20

SYSTEM_PROMPT = """
You are a friendly AI assistant.

Rules:
1. Be helpful.
2. Be professional.
3. Keep responses clean and concise.
4. Do not say you are an AI.
5. Reply in plain English without Markdown.
6. Remember previous conversation context.
"""

while True:
    try:
        user_input = input("\nYou: ")
    except (KeyboardInterrupt, EOFError):
        print("\nExiting...")
        break

    if user_input.lower() in ["bye", "exit", "quit"]:
        break

    # Add the user's message to the conversation history
    chat_history.append(f"User: {user_input}")

    # Keep only the most recent conversation history
    if len(chat_history) > MAX_HISTORY_LENGTH:
        chat_history = chat_history[-MAX_HISTORY_LENGTH:]

    # Build the prompt with the system instructions and conversation history
    conversation_prompt = (
        f"{SYSTEM_PROMPT}\n" + "\n".join(chat_history) + "\nAssistant: "
    )

    start_time = time.time()
    assistant_response = ""

    print("[bold green]Assistant:[/bold green] ", end="", flush=True)

    try:
        # Stream the response generated by Gemini
        response_stream = gemini_client.interactions.create(
            model="gemini-2.5-flash",
            input=conversation_prompt,
            stream=True,
        )

        for chunk in response_stream:
            if (
                chunk.event_type == "step.delta"
                and hasattr(chunk, "delta")
                and chunk.delta.type == "text"
            ):
                text_chunk = chunk.delta.text
                print(text_chunk, end="", flush=True)
                assistant_response += text_chunk

        response_time = time.time() - start_time

        print(f"\n\n[dim]Response time: {response_time:.2f} seconds[/dim]")

        # Store the assistant's response in the conversation history
        chat_history.append(f"Assistant: {assistant_response}")

    except Exception as error:
        print("\n[bold red]An error occurred while generating the response:[/bold red]")
        print(error)
        continue
