# Receive input -> Build prompt -> Call Gemini -> Create response -> Store response -> Return response

"""
Base Agent

Defines the common workflow and interface for all AI agents.

All AI agents should inherit from this class and implement
the required abstract methods.

Responsibilities:
1. Build the prompt using data from shared memory.
2. Send the prompt to the Gemini service.
3. Create an AgentResponse from the Gemini response.
4. Store the agent response in shared memory.
5. Return the final agent response.
"""

from abc import ABC, abstractmethod
from typing import Any

from memory.shared_memory import SharedMemory
from memory.conversation_memory import ConversationMemory
from models.agent_response import AgentResponse
from services.gemini_service import GeminiService
from knowledge.knowledge_base import KnowledgeBase


class BaseAgent(ABC):
    """
    Abstract base class for all AI agents.
    """

    def __init__(
        self,
        memory: SharedMemory,
        conversation_memory: ConversationMemory,
        gemini_service: GeminiService,
        knowledge_base: KnowledgeBase,
    ) -> None:
        """
        Initialize the base agent.

        Args:
            memory: Shared memory accessible by all agents.
            gemini_service: Service used to communicate with Gemini.
        """
        super().__init__()
        self.memory = memory
        self.gemini = gemini_service
        self.conversation_memory = conversation_memory
        self.knowledge_base = knowledge_base

    @abstractmethod
    def get_agent_name(self) -> str:
        """
        Return the name of the agent.

        Returns:
            str: The name of the agent, such as "Planner" or "Researcher".
        """
        pass

    @abstractmethod
    def get_memory_key(self) -> str:
        """
        Return the key used to store the agent's response in shared memory.

        Returns:
            str: The memory key where the agent's response should be stored.
        """
        pass

    @abstractmethod
    def build_prompt(self) -> str:
        """
        Build the prompt using data available in shared memory.

        Returns:
            str: The prompt to send to Gemini.
        """
        pass

    def execute(self) -> AgentResponse:
        """
        Execute the complete AI agent workflow.

        Workflow:
            Build prompt
            -> Call Gemini
            -> Create AgentResponse
            -> Store response in shared memory
            -> Return AgentResponse

        Returns:
            AgentResponse: The response generated by the agent.
        """
        agent_prompt = self.build_prompt()
        conversation = self.conversation_memory.get_context()
        Knowledge_context = self.knowledge_base.retrieve(
            self.memory.get("user_query", "")
        )

        prompt = f""""
        Conversation History:
        ----------------------
        {conversation}

        Knowledge Base:
        ----------------------
        {Knowledge_context}
    
        Current Task:
        ----------------------
        {agent_prompt}
        """
        gemini_response = self.ask_gemini(prompt)

        self.conversation_memory.add_ai_message(gemini_response.text)

        agent_response = AgentResponse(
            agent_name=self.get_agent_name(),
            output=gemini_response.text,
        )

        self.memory.add(
            self.get_memory_key(),
            agent_response,
        )

        return agent_response

    def ask_gemini(self, prompt: str) -> Any:
        """
        Send a prompt to Gemini and return the API response.

        Args:
            prompt: The prompt to send to the Gemini API.

        Returns:
            Any: The complete response returned by the Gemini API.

        Raises:
            RuntimeError: If the Gemini API request fails.
        """
        return self.gemini.generate_response(prompt)
