# ==============================================================================
# Stateless vs. Stateful:
# - Stateless: Each request is independent and does not contain
#   information from previous requests.
# - Stateful: Each new request can include previous conversation
#   messages, allowing the application to maintain context.
#
# Message Types in LangChain:
# - HumanMessage: Represents input from the user.
# - AIMessage: Represents a response generated by the AI model.
# - SystemMessage: Defines the model's behavior, instructions,
#   or overall role.
#
# Context Management Strategies:
# - Last N messages: Keep only the most recent messages.
# - Summarization: Summarize older conversation history.
# - Long-term memory: Persist important information across sessions.
#
# RunnableLambda:
# A Runnable that allows a regular Python function to be used
# as part of a LangChain pipeline.
#
# MessagesPlaceholder:
# A placeholder used to dynamically insert conversation history
# into a prompt.
#
# Conversation Memory:
# Stores previous user and AI messages so they can be included
# in future requests.
#
# Context Management:
# Controls which parts of the conversation are provided to the model.
# ==============================================================================

import os

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.runnables import RunnableLambda
from langchain_core.output_parsers import StrOutputParser

load_dotenv()


# Verify that the Gemini API key is available.
google_api_key = os.getenv("GEMINI_API_KEY")
llm_model_name = "gemini-3.5-flash-lite"

if not google_api_key:
    raise ValueError("GEMINI_API_KEY environment variable is missing in .env file.")


class ConversationMemory:
    """
    Stores messages exchanged between the user and the AI.

    The stored messages can be included in subsequent requests,
    making the application stateful and allowing the AI to use
    previous conversation context.
    """

    def __init__(self):
        self.messages = []

    def add_user_message(self, question: str):
        """Add a user message to the conversation history."""
        self.messages.append(HumanMessage(content=question))

    def add_ai_message(self, answer: str):
        """Add an AI-generated message to the conversation history."""
        self.messages.append(AIMessage(content=answer))

    def get_messages(self):
        """Return the complete conversation history."""
        return self.messages

    def get_last_n_messages(self, n: int = 10):
        """Return the most recent N messages from the conversation."""
        return self.messages[-n:]

    def clear_messages(self):
        """Clear all messages from the conversation history."""
        self.messages.clear()


# Initialize the Gemini chat model.
model = ChatGoogleGenerativeAI(
    model=llm_model_name,
    temperature=0.5,
    google_api_key=google_api_key,
)


# Define the prompt template.
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful AI chat assistant. "
            "Solve the user's query in 1-2 lines. "
            "Use the previous conversation when it is relevant.",
        ),
        # Insert previous conversation history here.
        MessagesPlaceholder(variable_name="history"),
        # Insert the current user question here.
        ("human", "{question}"),
    ]
)


def preprocess_input(data: dict) -> dict:
    """
    Prepare user input and conversation history before
    passing them to the prompt template.

    Only the last 10 messages are included to limit the
    amount of conversation context sent to the model.
    """
    question = data["question"].strip()
    history = data["history"]

    # Keep only the 10 most recent messages.
    history = history[-10:]

    return {
        "question": question,
        "history": history,
    }


# Convert the Python preprocessing function into a LangChain Runnable.
preprocess = RunnableLambda(preprocess_input)


# Convert the model's response into a plain string.
output_parser = StrOutputParser()


# Initialize conversation memory.
memory = ConversationMemory()


# Build the LangChain pipeline:
#
# 1. preprocess -> Prepare the question and conversation history.
# 2. prompt     -> Build the final prompt using the prepared data.
# 3. model      -> Send the prompt to the Gemini model.
# 4. parser     -> Convert the model response into a string.
chain = preprocess | prompt | model | output_parser


def ask_ai(question: str):
    """
    Send a user question to the AI and update the conversation memory.
    """

    # Prepare the input using the current conversation history.
    data = {
        "question": question,
        "history": memory.get_messages(),
    }

    # Invoke the LangChain pipeline.
    response = chain.invoke(data)

    # Store both the user question and AI response
    # for future conversation turns.
    memory.add_user_message(question)
    memory.add_ai_message(response)

    return response


print("AI Chat Assistant")
print("Type 'exit' or 'quit' to stop.\n")


while True:
    print("=" * 70)
    user_input = input("👉 ")
    print("=" * 70)
    # Exit the application when the user enters "exit" or "quit".
    if user_input.lower().strip() in {"exit", "quit"}:
        print("Goodbye!")
        break

    # Ignore empty input.
    if not user_input.strip():
        continue

    # Send the user's question to the AI.
    ai_response = ask_ai(user_input)

    # Display the AI response.
    print("=" * 70)
    print(f"🤖: {ai_response}\n")
    print("=" * 70)
