"""
Conversation Memory

Maintains the conversation history between the user and the AI application.

Responsibilities:
1. Store user messages.
2. Store AI responses.
3. Retrieve the complete conversation history.
4. Provide conversation context for AI agents.
"""

from typing import List

from rich import print


class ConversationMemory:
    """
    Maintains the conversation history between the user and the AI application.

    Stored messages can be included in prompts to provide AI agents
    with the necessary context from the ongoing conversation.
    """

    def __init__(self) -> None:
        """
        Initialize an empty conversation history.
        """
        self._messages: List[str] = []

    def add_user_message(self, message: str) -> None:
        """
        Store a message sent by the user.

        Args:
            message: The user's message.
        """
        self._messages.append(f"User: {message}")

    def add_ai_message(self, message: str) -> None:
        """
        Store a response generated by the AI.

        Args:
            message: The AI-generated response.
        """
        self._messages.append(f"Assistant: {message}")

    def get_context(self) -> str:
        """
        Return the complete conversation history as a single string.

        Returns:
            str: The conversation history with each message on a new line.
        """
        return "\n".join(self._messages)

    def clear(self) -> None:
        """
        Clear the entire conversation history.
        """
        self._messages.clear()

    def display(self, max_length: int = 120) -> None:
        """
        Display the current conversation history using Rich.

        This method is primarily useful for debugging and inspecting
        the current state of the conversation memory.

        Args:
            max_length: The maximum length of each message to display.
                Defaults to 120 characters.
        """
        separator = "=" * 60

        print(f"\n[dim]{separator}[/dim]")
        print("[bold magenta]Conversation Memory[/bold magenta]")
        print(f"[dim]{separator}[/dim]")

        if not self._messages:
            print("[italic yellow]No conversation history available.[/italic yellow]")
        else:
            for message in self._messages:
                preview = message[:max_length] + "..."
                print(f"[cyan]{preview}[/cyan]")

        print(f"[dim]{separator}[/dim]\n")
