"""
Shared Memory

Provides a common storage mechanism that can be accessed by all agents.

Responsibilities:
1. Store data generated by agents.
2. Retrieve data required by other agents.
3. Provide a common communication mechanism between agents.
4. Remain independent of any specific agent.
"""

from typing import Any

from rich import print


class SharedMemory:
    """
    Shared memory accessible by all agents.
    """

    def __init__(self) -> None:
        self._memory: dict[str, Any] = {}

    def add(self, key: str, value: Any) -> None:
        """
        Store data in shared memory under the given key.

        Args:
            key: Unique identifier for the stored data.
            value: Data to store.
        """
        self._memory[key] = value

    def get(self, key: str, default: Any = None) -> Any:
        """
        Retrieve data from shared memory by key.

        Args:
            key: Key to look up.
            default: Value to return if the key does not exist.

        Returns:
            The stored value, or the default value if the key is not found.
        """
        return self._memory.get(key, default)

    def exists(self, key: str) -> bool:
        """
        Check whether a key exists in shared memory.

        Args:
            key: Key to check.

        Returns:
            True if the key exists, otherwise False.
        """
        return key in self._memory

    def clear(self) -> None:
        """
        Remove all data from shared memory.
        """
        self._memory.clear()

    def remove(self, key: str) -> None:
        """
        Remove a key and its associated value from shared memory.

        Args:
            key: Key to remove.
        """
        self._memory.pop(key, None)

    def get_all(self) -> dict[str, Any]:
        """
        Retrieve all stored data.

        Returns:
            A dictionary containing all stored key-value pairs.
        """
        return self._memory.copy()

    def display(self) -> None:
        """
        Display the current contents of shared memory using Rich.
        """
        print(f"[bold cyan]{'=' * 60}[/bold cyan]")

        if not self._memory:
            print("[italic yellow]Shared memory is currently empty.[/italic yellow]")
        else:
            for key, value in self._memory.items():
                print(f"[bold green]{key}:[/bold green] {value}")

        print(f"[bold cyan]{'=' * 60}[/bold cyan]\n")
