"""
Agent Response Model

Represents the standardized response returned by every AI agent.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# NOTE:
# @dataclass is a Python decorator that automatically generates common
# methods such as __init__() for classes that primarily store data.
@dataclass
class AgentResponse:
    """
    Standardized response returned by every AI agent.
    """

    # Name of the agent that generated the response.
    agent_name: str

    # Output generated by the AI agent.
    output: str

    # Execution status of the agent.
    status: str = "SUCCESS"

    # Error message, if the agent execution fails.
    error: Optional[str] = None

    # Timestamp when the response was generated.
    timestamp: datetime = field(default_factory=datetime.now)

    def is_success(self) -> bool:
        """
        Return True if the agent execution was successful.
        """
        return self.status.upper() == "SUCCESS"

    def __str__(self):
        """
        Return a readable string representation of the agent response.
        """
        return (
            f"\nAgent: {self.agent_name}"
            f"\nStatus: {self.status}"
            f"\nTimestamp: {self.timestamp}"
            f"\nOutput: {self.output}"
        )
